title: My blog
description: My very nice blog
author: "Jorge Sanz"

theme: jekyll-theme-cayman

base_url: /blog

# Minima social links
github_username: jakelevinez
linkedin_username: jacob-levine-0a5497a9

# Minima: show excerpts in the frontpage
show_excerpts: true

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - README.md
