title: Jake's Blog
description: My journey in Devops, SRE, and other tech topics
show_downloads: false

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://jakelevinez.github.io/" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: jakelevinez
image: /thumbnail-jumbo.png
linkedin:
  username: jacob-levine-0a5497a9

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
